services:

  database:
    container_name: nuxt-rails-database
    build: ./database
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - network

  backend:
    container_name: nuxt-rails-backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - network

  frontend:
    container_name: nuxt-rails-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network

volumes:
  volume:

networks:
  network:
