default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: database
  port: 5432
  pool: 5

development:
  <<: *default
  database: railsapp_development

test:
  <<: *default
  database: railsapp_test

production:
  <<: *default
  database: railsapp_production
