source "https://rubygems.org"

ruby "3.3.4"

# Rails本体
gem "rails", "~> 7.1.3", ">= 7.1.3.4"

# アセットパイプライン
gem "sprockets-rails"

# postgresql DB
gem "pg", "~> 1.1"

# WEBサーバー
gem "puma", ">= 5.0"

# JS import-map
gem "importmap-rails"

# モダンフロント (Hotwire = turbo + stimulus)
gem "turbo-rails"
gem "stimulus-rails"

# 暗号化
gem "bcrypt", "~> 3.1.7"

# キャッシュ
gem "bootsnap", require: false


group :development, :test do
  # デバッグ
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  # WEBコンソール
  gem "web-console"
end

group :test do
  # テスト
  gem "capybara"
  gem "selenium-webdriver"
end
