version: "3.7"

services:

  database:
    container_name: railsapi-database
    build: ./database
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - network

  backend:
    container_name: railsapi-backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - network

  frontend:
    container_name: railsapi-frontend
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - network
    # tty: true　初回起動時のみ

volumes:
  volume:

networks:
  network:
